### ISSUE TITLE
Unbinding specific events not working

### ISSUE THREAD

**Issue by JohnKis** [taye/interact.js#149]
First of all, thanks for all your handwork on interact.js. It's a great library to work with.

Today I've noticed that unbinding events isn't working. When I call .off('drop') on an interactable, the event listener will still be active. I've tried to debug it and found that events.remove() (in line 413) expects an element as opposed to an interactable (which .off() passes through), hence it'll bail out in line 421 as 'target' will be undefined.

**Comment by taye** [comment]
Thanks for raising this issue. I've released a new version which fixes it.

**Comment by JohnKis** [comment]
Thanks for your quick response.

Something's still wrong, though. Removing an action event listener is still not working.
The following code should bind an event listener to 'drop' and then unbind it. However the listener will still be called after unbinding. 
```javascript
interact(el)
	.dropzone(true)
	.on('drop',function(){
		alert('drop');
	});

interact(el)
	.dropzone(false)
	.off('drop',function(){
		alert('drop');
	});
```


Logging this._iEvents in :4802 shows that the event listener has been successfully removed, but it will still be called.

**Comment by taye** [comment]
That's because those functions are two different objects. If you do add and remove the events like this instead, then it should work:

```javascript
function dropListener (event){
    alert('drop');
}

interact(el)
    .dropzone(true)
    .on('drop', dropListener);

interact(el)
    .dropzone(false)
    .off('drop', dropListener);
```

**Comment by JohnKis** [comment]
Sorry, that's how I'm using it. I just got it wrong in the example. Logging out this._iEvents clearly shows that the listener has been removed, however it'll be fired again somehow after removal.

**Comment by taye** [comment]
Maybe you added the event by including it in the dropzone options.

```javascript
interact(el).dropzone({
  ondrop: dropListener
});
```

In that case, you would have to do:

```javascript
interact(el).ondrop = null;
```

**Comment by JohnKis** [comment]
I haven't used it that way, but I tried your suggestion and it worked fine.

Thanks very much for your help!

**Comment by taye** [comment]
You're welcome :)

**Comment by homerjam** [comment]
> That's because those functions are two different objects. If you do add and remove the events like this instead, then it should work:
> 
> ```js
> function dropListener (event){
>     alert('drop');
> }
> 
> interact(el)
>     .dropzone(true)
>     .on('drop', dropListener);
> 
> interact(el)
>     .dropzone(false)
>     .off('drop', dropListener);
> ```

I seem to be having trouble with this method of event binding/unbinding. Is there a way to destroy the Interactable altogether?
