### ISSUE TITLE
"restrict.endOnly = true" has a little problem in "resizable" and "gesturable"

### ISSUE THREAD

**Issue by faller** [taye/interact.js#314]
demo:  http://jsfiddle.net/tsLao12y/

"endOnly within resizable" does not work on "https://rawgit.com/taye/interact.js/unstable/dist/interact.js" but it works on "http://code.interactjs.io/v1.2.6/interact.js"

"endOnly within gesturable" does not work on both "unstable" and "v1.2.6"

Thank's for your great job, I like interact very much.

**Comment by taye** [comment]
Fixed and bundled in `unstable`. Thanks for reporting.

**Comment by faller** [comment]
Thanks, @taye . It works with resizable, but still not work with gesturable.

Here is a demo of gesturable: http://jsfiddle.net/Ls9xe645/

**Comment by faller** [comment]
How can I disable resizable from touching?  I want it just on mousing.
I tried detecting "interact.supportsTouch()", but it seems not a good idea because some laptops supports both touching and mousing. 
Thank you for answering.

**Comment by taye** [comment]
Resize restrictions have been [broken](#84) for a while. For now you'll have to implement your own restriction in your resizemove handlers.

You can use a custom [action checker](http://interactjs.io/api/#Interactable.actionChecker) like this:

```javascript
interact(target).actionChecker(function (pointer, event, action) {
  // if the defauilt action is a resize and the pointer is a touch
  if (action && action.name === 'resize' && /touch/.test(event.pointerType || event.type)) {
    // return no action
    return null;
  }

  // otherwise return the default action
  return action;
});

Gesture restriction works if you use `event.pageX/Y` and `event.dx/xy`. The `box` property uses the actual pointer coordinates.

**Comment by faller** [comment]
thanks a lot
