### ISSUE TITLE
'allowFrom' does not exist in type 'DraggableOptions'.

### ISSUE THREAD

**Issue by md13381** [taye/interact.js#627]
Following the example in the documentation for using allowFrom and downloading the latest stable using npm (1.3.3) in an angular application this error is displayed during compiling

### Expected behavior
Allow the use of a button as the allowable drag able trigger

### Actual behavior
An error is displayed during compiling: 'allowFrom' does not exist in type 'DraggableOptions'.
```
import * as interact from 'interactjs';

interact('.draggable')
      .draggable({
        inertia: false,
        allowFrom: '[drag-handle]',
        onmove: this.dragMoveListener,
      });
```
On investigation it seems to be missing this form the index.d.ts file, when adding this as an option the code works as intended

**Comment by caio92** [comment]
Hey there,
I'm having a similar issue, but with different options, such as 'enabled', 'restrictEdges' for .resizable and the unset() method. It seems that the index.d.ts file is a bit outdated... :/

But besides that, this is an excellent module, congratulations for your work @taye! :)

**Comment by JonathanWilbur** [comment]
@caio92 , it looks like this is fixed in the 1.4.0 betas, but those have not been released to npm yet. I would give it a few days.

**Comment by angeenes** [comment]
Hi, any news about the v1.4.0 release on npm ?

**Comment by taye** [comment]
@angeenes probably not for another month at least. I still have a lot of documentation to write. You can `npm install interactjs@next` for now.

**Comment by taye** [comment]
I'm closing this as the typing issues have been resolved in the latest 1.4.0-alpha releases. I'd still really appreciate help with the docs! A short list of article headings and examples for a new guide would be a great place to start. Shout at me (nicely) in https://gitter.im/taye/interact.js.
